// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: AssemblyCompanyAttribute("MyCompany")]
[assembly: AssemblyCopyrightAttribute("MyCompany")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.0";
        internal const System.String AssemblyInformationalVersion = "1.0.0";
        internal const System.String AssemblyCompany = "MyCompany";
        internal const System.String AssemblyCopyright = "MyCompany";
        internal const System.Boolean ComVisible = false;
    }
}
